### ISSUE TITLE
Aplikace padá při POST na /result

### ISSUE THREAD

**Issue by zoul** [cesko-digital/skill-matcher#8]
Logy z AWS:

```
[ERROR]	2023-08-28T16:29:39.016Z	07e40008-5531-4f1b-b4aa-2e11cb5d9ea7	Exception on /result [POST]
Traceback (most recent call last):
  File "/var/task/app.py", line 388, in result
    engine = sqlalchemy.create_engine(conn)
  File "<string>", line 2, in create_engine
  File "/tmp/sls-py-req/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/tmp/sls-py-req/sqlalchemy/engine/create.py", line 518, in create_engine
    entrypoint = u._get_entrypoint()
  File "/tmp/sls-py-req/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
    cls = registry.load(name)
  File "/tmp/sls-py-req/sqlalchemy/util/langhelpers.py", line 341, in load
    return impl.load()
  File "/var/lang/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/sls-py-req/snowflake/sqlalchemy/__init__.py", line 30, in <module>
    from . import base, snowdialect
  File "/tmp/sls-py-req/snowflake/sqlalchemy/base.py", line 16, in <module>
    from .util import _set_connection_interpolate_empty_sequences
  File "/tmp/sls-py-req/snowflake/sqlalchemy/util.py", line 11, in <module>
    from snowflake.connector.compat import IS_STR
  File "/tmp/sls-py-req/snowflake/connector/__init__.py", line 17, in <module>
    from .connection import SnowflakeConnection
  File "/tmp/sls-py-req/snowflake/connector/connection.py", line 29, in <module>
    from .auth import (
  File "/tmp/sls-py-req/snowflake/connector/auth/__init__.py", line 7, in <module>
    from ._auth import Auth, get_public_key_fingerprint, get_token_from_private_key
  File "/tmp/sls-py-req/snowflake/connector/auth/_auth.py", line 21, in <module>
    from cryptography.hazmat.primitives.serialization import (
  File "/tmp/sls-py-req/cryptography/hazmat/primitives/serialization/__init__.py", line 16, in <module>
    from cryptography.hazmat.primitives.serialization.base import (
  File "/tmp/sls-py-req/cryptography/hazmat/primitives/serialization/base.py", line 9, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import (
  File "/tmp/sls-py-req/cryptography/hazmat/primitives/asymmetric/types.py", line 8, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "/tmp/sls-py-req/cryptography/hazmat/primitives/asymmetric/dsa.py", line 10, in <module>
    from cryptography.hazmat.primitives.asymmetric import utils as asym_utils
  File "/tmp/sls-py-req/cryptography/hazmat/primitives/asymmetric/utils.py", line 6, in <module>
    from cryptography.hazmat.bindings._rust import asn1
ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/sls-py-req/cryptography/hazmat/bindings/_rust.abi3.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/sls-py-req/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/sls-py-req/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/sls-py-req/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/sls-py-req/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/task/app.py", line 392, in result
    conn = snowflake.connector.connect(
AttributeError: module 'snowflake' has no attribute 'connector'
```

**Comment by zoul** [comment]
Vypadá to, že 28d3316d8e37a282b57b62eed09cf825ddb8a5be zabralo.
